CREATE TABLE TB_PARCEIRO (
    parceiroId INTEGER NOT NULL PRIMARY KEY,
    nome VARCHAR(150) NOT NULL
);

CREATE TABLE TB_PRODUTO (
    produtoId INTEGER NOT NULL,
    nome VARCHAR(150) NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    quantidadeAcionamento INTEGER NOT NULL,
    parceiroId INTEGER NOT NULL,
    PRIMARY KEY (produtoId)
);

ALTER TABLE TB_PRODUTO
ADD FOREIGN KEY (parceiroId) REFERENCES TB_PARCEIRO(parceiroId);
